### ISSUE TITLE
Redirect Interviewer Applications to Lever Jobs Page

### ISSUE THREAD

**Issue by jcs150** [Karat/karat-public#43]
Update Interviewers page on our website to look like the attached and to refer candidates to this page: https://jobs.lever.co/karat/d44ab283-c7c0-4bbd-b8c3-4dc0ced64c86

![pasted image at 2016_01_07 02_22 pm](https://cloud.githubusercontent.com/assets/5280687/12201604/4ceb5cb2-b5f3-11e5-8e73-b91202c35ccf.png)

**Comment by neilkumar** [comment]
adding @apr35
